-- EPH Proje Satış Merkezi V2
-- Standart cephe sayıları ve genişletilmiş bağımsız bölüm türleri

ALTER TYPE "ProjectGeometryType" ADD VALUE IF NOT EXISTS 'CIFT_CEPHELI_STANDART';
ALTER TYPE "ProjectGeometryType" ADD VALUE IF NOT EXISTS 'UC_CEPHELI_STANDART';
ALTER TYPE "ProjectGeometryType" ADD VALUE IF NOT EXISTS 'DORT_CEPHELI_STANDART';

ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'STUDYO';
ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'TERAS_LOFT';
ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'DUBLEKS';
ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'TRIPLEKS';
ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'MARKET';
ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'MUAYENEHANE';
ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'KLINIK';
ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'OTEL_ODASI';
