ALTER TYPE "KontorIslemTuru"
ADD VALUE IF NOT EXISTS 'FORUM_MESAJ';

ALTER TYPE "KontorIslemTuru"
ADD VALUE IF NOT EXISTS 'FORUM_ILGILENIYORUM';

ALTER TYPE "KontorIslemTuru"
ADD VALUE IF NOT EXISTS 'FORUM_YARDIMCI_OLABILIRIM';
