export const STATUS_LABELS: Record<string, string> = {
  SATILIK: "Satılık",
  KIRALIK: "Kiralık",
  GUNLUK_KIRALIK: "Günlük Kiralık",
  DEVREN_SATILIK: "Devren Satılık",
  DEVREN_KIRALIK: "Devren Kiralık",
  ON_SATIS: "Ön Satış",
  PROJE_ASAMASI: "Proje Aşaması",
  YAKINDA_SATISTA: "Yakında Satışta",
  INSAAT_HALINDE: "İnşaat Halinde",
  TESLIME_HAZIR: "Teslime Hazır",
  HEMEN_TESLIM: "Hemen Teslim",
  INSAAT_PROJESI: "İnşaat Projesi",
  KAT_KARSILIGI: "Kat Karşılığı",
  HASILAT_PAYLASIMLI: "Hasılat Paylaşımlı",
  REZERVE: "Rezerve",
  SATILDI: "Satıldı",
  KIRALANDII: "Kiralandı",
  PASIF: "Pasif",
};

export const STATUS_COLORS: Record<string, { color: string; bg: string; border: string; dot: string }> = {
  SATILIK: { color: "#067647", bg: "#ECFDF3", border: "#ABEFC6", dot: "#17B26A" },
  KIRALIK: { color: "#175CD3", bg: "#EFF8FF", border: "#B2DDFF", dot: "#2E90FA" },
  GUNLUK_KIRALIK: { color: "#175CD3", bg: "#EFF8FF", border: "#B2DDFF", dot: "#2E90FA" },
  DEVREN_SATILIK: { color: "#6941C6", bg: "#F4F3FF", border: "#D9D6FE", dot: "#7A5AF8" },
  DEVREN_KIRALIK: { color: "#6941C6", bg: "#F4F3FF", border: "#D9D6FE", dot: "#7A5AF8" },
  ON_SATIS: { color: "#B54708", bg: "#FFFAEB", border: "#FEDF89", dot: "#F79009" },
  PROJE_ASAMASI: { color: "#B54708", bg: "#FFFAEB", border: "#FEDF89", dot: "#F79009" },
  YAKINDA_SATISTA: { color: "#B54708", bg: "#FFFAEB", border: "#FEDF89", dot: "#F79009" },
  INSAAT_HALINDE: { color: "#B54708", bg: "#FFFAEB", border: "#FEDF89", dot: "#F79009" },
  TESLIME_HAZIR: { color: "#067647", bg: "#ECFDF3", border: "#ABEFC6", dot: "#17B26A" },
  HEMEN_TESLIM: { color: "#067647", bg: "#ECFDF3", border: "#ABEFC6", dot: "#17B26A" },
  INSAAT_PROJESI: { color: "#B54708", bg: "#FFFAEB", border: "#FEDF89", dot: "#F79009" },
  KAT_KARSILIGI: { color: "#B54708", bg: "#FFFAEB", border: "#FEDF89", dot: "#F79009" },
  HASILAT_PAYLASIMLI: { color: "#B54708", bg: "#FFFAEB", border: "#FEDF89", dot: "#F79009" },
  REZERVE: { color: "#93370D", bg: "#FFF6ED", border: "#FED7AA", dot: "#FB6514" },
  SATILDI: { color: "#344054", bg: "#F2F4F7", border: "#D0D5DD", dot: "#667085" },
  KIRALANDII: { color: "#344054", bg: "#F2F4F7", border: "#D0D5DD", dot: "#667085" },
  PASIF: { color: "#344054", bg: "#F2F4F7", border: "#D0D5DD", dot: "#667085" },
};

export const TYPE_LABELS: Record<string, string> = {
  DAIRE: "Daire",
  REZIDANS: "Rezidans",
  VILLA: "Villa",
  VILLA_TERAS: "Villa Teras",
  VILLA_GARDEN: "Villa Garden",
  DUBLEKS_VILLA: "Dubleks Villa",
  TRIPLEKS_VILLA: "Tripleks Villa",
  MUSTAK_EV: "Müstakil Ev",
  KOY_EVI: "Köy Evi",
  TAS_EV: "Taş Ev",
  AHSAP_EV: "Ahşap Ev",
  PREFABRIK_EV: "Prefabrik Ev",
  CELIK_KONSTRUKSIYON: "Çelik Konstrüksiyon",
  TINY_HOUSE: "Tiny House",
  BUNGALOV: "Bungalov",
  DAG_EVI: "Dağ Evi",
  YAYLA_EVI: "Yayla Evi",
  GOL_EVI: "Göl Evi",
  BAG_EVI: "Bağ Evi",
  CIFTLIK_EVI: "Çiftlik Evi",
  HOBI_BAHCESI_EVI: "Hobi Bahçesi Evi",
  MAGARA_EV: "Mağara Ev",
  KOSK_YALI: "Köşk/Yalı",
  YALI: "Yalı",
  YALI_DAIRESI: "Yalı Dairesi",
  KONAK: "Konak",
  PENTHOUSE: "Penthouse",
  LOFT: "Loft",
  LOFT_DUBLEKS: "Loft Dubleks",
  MARINA_RESIDENCE: "Marina Residence",
  GOLF_RESIDENCE: "Golf Residence",
  SAHIL_RESIDENCE: "Sahil Residence",
  DAG_RESIDENCE: "Dağ Residence",
  SKY_RESIDENCE: "Sky Residence",
  OZEL_HAVUZLU_VILLA: "Özel Havuzlu Villa",
  OZEL_ISKELELI_VILLA: "Özel İskeleli Villa",
  AKILLI_VILLA: "Akıllı Villa",
  ULTRA_LUKS_VILLA: "Ultra Lüks Villa",
  DUKKAN_MAGAZA: "Dükkan/Mağaza",
  OFIS_BURO: "Ofis/Büro",
  HOME_OFFICE: "Home Office",
  PLAZA_KATI: "Plaza Katı",
  SHOWROOM: "Showroom",
  IS_HANI_KATI: "İş Hanı Katı",
  IS_MERKEZI: "İş Merkezi",
  PAYLASIMLI_OFIS: "Paylaşımlı Ofis",
  DEPO_ANTREPO: "Depo/Antrepo",
  LOJISTIK_MERKEZI: "Lojistik Merkezi",
  FABRIKA_ATOLYE: "Fabrika/Atölye",
  URETIM_TESISI: "Üretim Tesisi",
  AKARYAKIT_ISTASYONU: "Akaryakıt İstasyonu",
  OTEL_PANSIYON: "Otel/Pansiyon",
  APART_OTEL: "Apart Otel",
  RESTORAN: "Restoran",
  KAFE: "Kafe",
  DUGUN_SALONU: "Düğün Salonu",
  SPOR_TESISI: "Spor Tesisi",
  OKUL_EGITIM_TESISI: "Okul/Eğitim Tesisi",
  HASTANE_SAGLIK_TESISI: "Hastane/Sağlık Tesisi",
  KOMPLE_BINA: "Komple Bina",
  ARSA: "Arsa",
  KONUT_ARSASI: "Konut Arsası",
  VILLA_ARSASI: "Villa Arsası",
  TICARI_ARSA: "Ticari Arsa",
  SANAYI_ARSASI: "Sanayi Arsası",
  TURIZM_IMARLI_ARSA: "Turizm İmarlı Arsa",
  TARLA: "Tarla",
  BAHCE: "Bahçe",
  BAG: "Bağ",
  ZEYTINLIK: "Zeytinlik",
  MEYVE_BAHCESI: "Meyve Bahçesi",
  SERA: "Sera",
  BESI_CIFTLIGI: "Besi Çiftliği",
  ORMAN_ARAZISI: "Orman Arazisi",
  ADA: "Ada",
  DEVRE_MULK: "Devre Mülk",
  TURISTIK_TESIS: "Turistik Tesis",
  KONUT_PROJESI: "Konut Projesi",
  VILLA_PROJESI: "Villa Projesi",
  REZIDANS_PROJESI: "Rezidans Projesi",
  KARMA_PROJE: "Karma Proje",
  AVM_PROJESI: "AVM Projesi",
  TICARI_PROJE: "Ticari Proje",
};

export const ROOM_COUNT_OPTIONS = [
  "Studio", "1+0", "1+1", "1,5+1", "2+1", "2,5+1", "3+1", "3+2", "3,5+1", "3,5+2",
  "4+1", "4+2", "4,5+1", "4,5+2", "5+1", "5+2", "5+3", "6+1", "6+2", "6+3",
  "7+1", "7+2", "8+1", "8+2", "9+1", "9+2", "10+1", "10+2", "10+3", "10+4",
  "Loft", "Loft Dubleks", "Penthouse", "Özel Plan",
];

export const STATUS_GROUPS = [
  { label: "Satış", statuses: ["SATILIK", "DEVREN_SATILIK", "ON_SATIS", "YAKINDA_SATISTA", "HEMEN_TESLIM", "TESLIME_HAZIR"] },
  { label: "Proje", statuses: ["PROJE_ASAMASI", "INSAAT_HALINDE", "INSAAT_PROJESI", "KAT_KARSILIGI", "HASILAT_PAYLASIMLI"] },
  { label: "Kiralık", statuses: ["KIRALIK", "GUNLUK_KIRALIK", "DEVREN_KIRALIK"] },
  { label: "Diğer", statuses: ["REZERVE", "SATILDI", "KIRALANDII", "PASIF"] },
];

export const CITIES = ["Adana","Adıyaman","Afyonkarahisar","Ağrı","Amasya","Ankara","Antalya","Artvin","Aydın","Balıkesir","Bilecik","Bingöl","Bitlis","Bolu","Burdur","Bursa","Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Edirne","Elazığ","Erzincan","Erzurum","Eskişehir","Gaziantep","Giresun","Gümüşhane","Hakkari","Hatay","Isparta","İçel","İstanbul","İzmir","Kars","Kastamonu","Kayseri","Kırklareli","Kırşehir","Kocaeli","Konya","Kütahya","Malatya","Manisa","Kahramanmaraş","Mardin","Muğla","Muş","Nevşehir","Niğde","Ordu","Rize","Sakarya","Samsun","Siirt","Sinop","Sivas","Tekirdağ","Tokat","Trabzon","Tunceli","Şanlıurfa","Uşak","Van","Yozgat","Zonguldak","Aksaray","Bayburt","Karaman","Kırıkkale","Batman","Şırnak","Bartın","Ardahan","Iğdır","Yalova","Karabük","Kilis","Osmaniye","Düzce"];
