export type StokFeatureGroup = {
  key: string;
  label: string;
  options: string[];
};

export const STOK_FEATURE_GROUPS: Record<string, StokFeatureGroup> = {
  interior: {
    key: "interior",
    label: "İç Özellikler",
    options: [
      "ADSL",
      "Ahşap Doğrama",
      "Akıllı Ev",
      "Alarm (Hırsız)",
      "Alarm (Yangın)",
      "Alaturka Tuvalet",
      "Alüminyum Doğrama",
      "Amerikan Kapı",
      "Ankastre Fırın",
      "Barbekü",
      "Beyaz Eşya",
      "Boyalı",
      "Bulaşık Makinesi",
      "Buzdolabı",
      "Çamaşır Kurutma Makinesi",
      "Çamaşır Makinesi",
      "Çamaşır Odası",
      "Çelik Kapı",
      "Duşakabin",
      "Duvar Kağıdı",
      "Ebeveyn Banyosu",
      "Fiber İnternet",
      "Giyinme Odası",
      "Görüntülü Diafon",
      "Hilton Banyo",
      "Intercom Sistemi",
      "Isıcam",
      "Jakuzi",
      "Kapalı / Cam Balkon",
      "Kartonpiyer",
      "Kiler",
      "Klima",
      "Küvet",
      "Laminat Zemin",
      "Mobilya",
      "Mutfak (Ankastre)",
      "Mutfak Doğalgazı",
      "Panjur / Jaluzi",
      "Parke Zemin",
      "PVC Doğrama",
      "Seramik Zemin",
      "Set Üstü Ocak",
      "Spot Aydınlatma",
      "Şömine",
      "Teras",
      "Termosifon",
      "Vestiyer",
      "Yüz Tanıma & Parmak İzi",
    ],
  },
  exterior: {
    key: "exterior",
    label: "Dış Özellikler",
    options: [
      "Araç Şarj İstasyonu",
      "24 Saat Güvenlik",
      "Apartman Görevlisi",
      "Buhar Odası",
      "Çocuk Oyun Parkı",
      "Hamam",
      "Hidrofor",
      "Isı Yalıtımı",
      "Jeneratör",
      "Kablo TV",
      "Kamera Sistemi",
      "Köpek Parkı",
      "Kreş",
      "Müstakil Havuzlu",
      "Sauna",
      "Ses Yalıtımı",
      "Siding",
      "Spor Alanı",
      "Su Deposu",
      "Tenis Kortu",
      "Uydu",
      "Yangın Merdiveni",
      "Yüzme Havuzu (Açık)",
      "Yüzme Havuzu (Kapalı)",
      "Bahçe Terası",
      "Çatı Terası",
      "Özel Havuz",
      "Sonsuzluk Havuzu",
    ],
  },
  location: {
    key: "location",
    label: "Muhit",
    options: [
      "Alışveriş Merkezi",
      "Belediye",
      "Cami",
      "Cemevi",
      "Denize Sıfır",
      "Eczane",
      "Eğlence Merkezi",
      "Fuar",
      "Göle Sıfır",
      "Hastane",
      "Havra",
      "İlkokul-Ortaokul",
      "İtfaiye",
      "Kilise",
      "Lise",
      "Market",
      "Park",
      "Plaj",
      "Polis Merkezi",
      "Sağlık Ocağı",
      "Semt Pazarı",
      "Spor Salonu",
      "Şehir Merkezi",
      "Üniversite",
      "Köy Merkezi",
      "Köy Yakını",
      "Doğa İçinde",
    ],
  },
  transport: {
    key: "transport",
    label: "Ulaşım",
    options: [
      "Anayol",
      "Avrasya Tüneli",
      "Boğaz Köprüleri",
      "Cadde",
      "Deniz Otobüsü",
      "Dolmuş",
      "E-5",
      "Havaalanı",
      "İskele",
      "Marmaray",
      "Metro",
      "Metrobüs",
      "Minibüs",
      "Otobüs Durağı",
      "Sahil",
      "TEM",
      "Tramvay",
      "Tren İstasyonu",
      "Kadastral Yol",
      "Stabilize Yol",
      "Asfalt Yol",
    ],
  },
  front: {
    key: "front",
    label: "Cephe",
    options: ["Batı", "Doğu", "Güney", "Kuzey", "Köşe Parsel", "Çift Cephe", "Cadde Cepheli"],
  },
  view: {
    key: "view",
    label: "Manzara",
    options: [
      "Boğaz",
      "Deniz",
      "Doğa",
      "Göl",
      "Havuz",
      "Nehir",
      "Park & Yeşil Alan",
      "Şehir",
      "Dağ",
      "Vadi",
      "Panoramik",
      "Marina",
      "Golf Sahası",
    ],
  },
  accessibility: {
    key: "accessibility",
    label: "Engelliye / Yaşlıya Uygun",
    options: [
      "Araç Park Yeri",
      "Engelliye Uygun Asansör",
      "Engelliye Uygun Banyo",
      "Engelliye Uygun Mutfak",
      "Engelliye Uygun Park",
      "Geniş Koridor",
      "Giriş / Rampa",
      "Merdiven",
      "Oda Kapısı",
      "Priz / Elektrik Anahtarı",
      "Tutamak / Korkuluk",
      "Tuvalet",
      "Yüzme Havuzu",
    ],
  },
  zoning: {
    key: "zoning",
    label: "Tapu / İmar",
    options: [
      "Müstakil Tapu",
      "Hisseli Tapu",
      "Kat İrtifakı",
      "Kat Mülkiyeti",
      "İfrazlı",
      "Tevhidli",
      "Konut İmarlı",
      "Villa İmarlı",
      "Ticari İmarlı",
      "Sanayi İmarlı",
      "Turizm İmarlı",
      "Konut + Ticaret",
      "İmarsız",
      "Sit Alanı",
      "Kat Karşılığına Uygun",
    ],
  },
  landInfrastructure: {
    key: "landInfrastructure",
    label: "Arazi Altyapısı",
    options: [
      "Su Var",
      "Elektrik Var",
      "Doğalgaz Yakın",
      "Sondaj / Kuyu Var",
      "Sulama Kanalı",
      "Artezyen",
      "Damlama Sulama",
      "Yola Cepheli",
      "Kadastral Yolu Var",
      "Çit Çevrili",
      "Dere Kenarı",
      "Göl Kenarı",
      "Tarım Yapılıyor",
      "Meyve Ağaçları Var",
      "Zeytin Ağaçları Var",
    ],
  },
  commercial: {
    key: "commercial",
    label: "Ticari Değer",
    options: [
      "Cadde Üzeri",
      "Köşe Konum",
      "Tabela Değeri Yüksek",
      "Yaya Trafiği Yoğun",
      "Araç Trafiği Yoğun",
      "Kiracılı",
      "Devren",
      "Depolu",
      "Bacalı",
      "WC Var",
      "Mutfak Var",
      "Yükleme Alanı",
      "Tır Girişli",
      "Rampa Var",
      "Otopark Var",
    ],
  },
  tourism: {
    key: "tourism",
    label: "Turistik Tesis Özellikleri",
    options: [
      "Açık Havuz",
      "Kapalı Havuz",
      "Spa",
      "Hamam",
      "Sauna",
      "Restoran",
      "Bar",
      "Toplantı Salonu",
      "Düğün Alanı",
      "Denize Sıfır",
      "Plaj Kullanımı",
      "Ruhsatlı",
      "Sezonluk İşletme",
      "12 Ay Açık",
    ],
  },
  luxury: {
    key: "luxury",
    label: "Lüks Özellikler",
    options: [
      "Özel Havuz",
      "Sonsuzluk Havuzu",
      "Bahçe Terası",
      "Çatı Terası",
      "Özel İskele",
      "Marina Bağlantısı",
      "Golf Sahasına Yakın",
      "Akıllı Ev Sistemi",
      "Yerden Isıtma",
      "Otomatik Panjur",
      "Giyinme Odası",
      "Sinema Odası",
      "Şarap Mahzeni",
      "Hizmetli Odası",
      "Panoramik Manzara",
      "Sky Pool",
    ],
  },
  eph: {
    key: "eph",
    label: "EPH Özel Etiketler",
    options: [
      "Yetkili Portföy",
      "Doğrulanmış Portföy",
      "Lina Kartına Uygun",
      "Yatırımlık Premium",
      "Pazarlığa Açık",
      "Acil Satılık",
      "Sadece EPH Üyelerine Özel",
      "Paylaşım Kartı Hazır",
      "Broker Onaylı",
      "Saha Kontrolü Yapıldı",
    ],
  },
};

export function getFeatureGroups(keys: string[]) {
  return keys.map((key) => STOK_FEATURE_GROUPS[key]).filter(Boolean);
}
